### ISSUE TITLE
the close icon (X) in the search modal doesn't close the modal on mobile

### ISSUE THREAD

**Issue by Extheoisah** [bitcoinsearch/tldr#129]
Current behaviour: 
- the close icon doesn't do anything

Expected behaviour:
- On mobile, the close icon should clear the input content and close the modal.
- On desktop, it should clear the content only.

transferred from: https://github.com/bitcointranscripts/transcription-review-front-end/issues/203

**Comment by IgboPharaoh** [comment]
#131
