### ISSUE TITLE
Styling Issue with banner and nav header

### ISSUE THREAD

**Issue by Extheoisah** [bitcoinsearch/tldr#136]
Current behavior: on scroll, the banner header covers the nav bar which makes it difficult to search without 1st closing the banner.

Expected behavior: The nav bar should be fixed at a height such that it remains below the banner. When the banner is closed, it should return to its original position.

![image](https://github.com/bitcoinsearch/tldr/assets/60826700/dd30bb12-f48c-4021-a1c1-6c013c4ae97d)

**Comment by Extheoisah** [comment]
Partially fixed in https://github.com/bitcoinsearch/tldr/pull/137

**Comment by IgboPharaoh** [comment]
#141 I believe this fixes this
