### ISSUE TITLE
update newsletter fields

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/tldr#210]
<img width="713" alt="Screen Shot 2024-03-07 at 8 33 41 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/61cc85a6-c9b7-415e-9a91-bda8f94f873c">

**Comment by adamjonas** [comment]
- Please change the sender name to "The Bitcoin Dev Project" from "Chaincode Labs"
<img width="171" alt="Screenshot 2024-03-18 at 1 47 30 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/7b3662f2-434a-4508-89fa-938431a91a3e">

- The post titles do not look like links. Let's try an underline.
<img width="306" alt="Screenshot 2024-03-18 at 1 53 29 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/12fafb7a-95dd-4e1a-9c6d-76f3eb9619e8">


- This is very hard to read. Can we insert some spacing on this opening paragraph?
<img width="1030" alt="Screenshot 2024-03-18 at 1 47 45 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/31877d68-71ee-4386-98cb-204effa2f27d">

**Comment by nully0x** [comment]
Alright, we act on this.

**Comment by adamjonas** [comment]
s/authors/author/

<img width="205" alt="Screenshot 2024-03-19 at 4 14 10 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/ae9e83b7-7b2d-42c2-af3b-944f9ea86e5b">

s/The Bitcoin Dev Project/Bitcoin Dev Project/

<img width="154" alt="Screenshot 2024-03-19 at 4 15 37 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/574fb87e-5cf2-4bf2-b862-1fbcb20b49a7">

**Comment by nully0x** [comment]
For "The Bitcoin Dev Project" usually some mail clients has limits to the number of characters to be displayed before opening the mail, you will notice that after opening the mail it's displayed in full. Should I change it to "The Bitcoin Dev"?

As for the author, there are some that has multiple names(seen a few before). I am not sure what that should be.

**Comment by adamjonas** [comment]
Then do author(s) instead.

Are you sure in the character limit? Cutting the and the space should give you 4 more characters, no?

**Comment by nully0x** [comment]
>  Are you sure in the character limit? Cutting the and the space should give you 4 more characters, no?

This is a delivery to my outlook mail. Some client truncate, some don't truncate. Gmail mostly truncate. Will use the new suggestion and redeliver again
![image](https://github.com/bitcoinsearch/tldr/assets/40327060/99b4463f-f1aa-4a48-bc6a-27888b04d912)
