### ISSUE TITLE
(regression) incorrect number of replies

### ISSUE THREAD

**Issue by Extheoisah** [bitcoinsearch/tldr#212]
The number of thread replies for some posts is incorrect. See screenshots below.
https://tldr.bitcoinsearch.xyz/summary/delvingbitcoin/Feb_2024/combined_Mempool-Incentive-Compatibility#discussion-history

![image](https://github.com/bitcoinsearch/tldr/assets/60826700/4b42657f-f43b-4082-be89-f721d2779c73)
![image](https://github.com/bitcoinsearch/tldr/assets/60826700/465443c3-e8e2-4f52-9ac3-c070ddc6e248)

**Comment by urvishp80** [comment]
This could have occurred due to parallel scheduling of GitHub Actions. I updated the time for json generation of homepage and newsletter files. I also ran the workflows in order generate the latest homepage.json. I also ran the `update submodules` action on this repo we the changes gets reflected on the website.

**Comment by urvishp80** [comment]
The code seems correct in the backend. 

If you take a look at this line in [`homepage.json`](https://github.com/bitcoinsearch/mailing-list-summaries/blob/08bdd2abcd8132e3aaf2eadc50816d4926a36047/static/homepage.json#L120) file's n_threads` it shows the number of replies.   
![image](https://github.com/bitcoinsearch/tldr/assets/26462893/953f4b7a-b73b-4f5e-bbff-4a331e9d777a)  
  
  

And the same no. of threads are shown in the discussion history of [this post](https://tldr.bitcoinsearch.xyz/summary/delvingbitcoin/March_2024/combined_Mempool-Incentive-Compatibility#discussion-history)
![image](https://github.com/bitcoinsearch/tldr/assets/26462893/6b7fced2-f9a1-4e79-8d78-0abbd8db4b5a)  

However on the homepage of [Bitcoin TLDR](https://tldr.bitcoinsearch.xyz/), it is not as per `homepage.json`.
![image](https://github.com/bitcoinsearch/tldr/assets/26462893/a6f9940b-bc28-4ab5-ba6e-3abe6e5a4243)  

@Extheoisah , Can you please take a look in the frontend code as well?

**Comment by Extheoisah** [comment]
found another bug related to replies:
![image](https://github.com/bitcoinsearch/tldr/assets/60826700/cae6e714-08c5-491d-91a1-58189f9fae33)

**Comment by urvishp80** [comment]
If you take a look [here](https://github.com/bitcoinsearch/mailing-list-summaries/blob/71e663e7f9c7d04fb97fa9ae56c2509ab9b9f5b1/static/homepage.json#L13), `n_threads` is already `0` so it should be the same on the frontend.
![image](https://github.com/bitcoinsearch/tldr/assets/26462893/0c9b8f79-88c0-475d-983d-0aa2e34c8566)

Can you please confirm that the frontend team is not preprocessing the value of `n_threads` (replies) which is being received from [`homepage.json`](https://github.com/bitcoinsearch/mailing-list-summaries/blob/main/static/homepage.json)?

**Comment by Extheoisah** [comment]
Issue has been resolved here https://github.com/bitcoinsearch/tldr/pull/218
