### ISSUE TITLE
Newsletter threads not linked to combined summaries

### ISSUE THREAD

**Issue by rejeses** [bitcoinsearch/tldr#260]
Some threads in newsletters are not linked to combined summaries. Here's a [screen recording of this](https://www.loom.com/share/a9433d07bcbb4b3fbc6fce3739a401ec?sid=b10b86b6-314c-486d-baa3-ceb5ce890565)

**Comment by nully0x** [comment]
Yes, I have highlighted this issue in one of the discussions, the issue stems from newsletter generation where the [newsletter.json](https://github.com/bitcoinsearch/mailing-list-summaries/blob/a2c589bd1e65dac5223a20df63f358dd98c2aa4e/static/newsletters/newsletter.json) missed some value needed to populate the email templates.

![image](https://github.com/bitcoinsearch/tldr/assets/40327060/29a79930-cc6f-47e7-9b75-e9493261f8f6)


As shown in the image above, you will notice that `"combined_summ_file_path": ""` is missing for two fields which represents the missing hyperlink in the newsletter. 

A hack around this is to use `"file_path"` where `"combined_summ_file_path": ""` is missing.

**Comment by Extheoisah** [comment]
> Yes, I have highlighted this issue in one of the discussions, the issue stems from newsletter generation where the [newsletter.json](https://github.com/bitcoinsearch/mailing-list-summaries/blob/a2c589bd1e65dac5223a20df63f358dd98c2aa4e/static/newsletters/newsletter.json) missed some value needed to populate the email templates.
> 
> ![image](https://private-user-images.githubusercontent.com/40327060/321019317-29a79930-cc6f-47e7-9b75-e9493261f8f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3MDQwMzYsIm5iZiI6MTcxMjcwMzczNiwicGF0aCI6Ii80MDMyNzA2MC8zMjEwMTkzMTctMjlhNzk5MzAtY2M2Zi00N2U3LTliNzUtZTk0OTMyNjFmOGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDIzMDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxY2ZmYmM2OTZlMjgzMjhjZWYyMGUxODkwMTUyNDA2NjU3OGIwZGY4MGIyOThmMTEwZDYyOGMxYTQyZjBkMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gOTeSsOdSGc7nRsQcE0oXNrnQ5qqnNM2iw1A3YUm1-U)
> 
> As shown in the image above, you will notice that `"combined_summ_file_path": ""` is missing for two fields which represents the missing hyperlink in the newsletter.
> 
> A hack around this is to use `"file_path"` where `"combined_summ_file_path": ""` is missing.

Lets go with the hack. that is what we do in the web app. See [here](https://github.com/bitcoinsearch/tldr/blob/339e61f85828b2e2a5697a392aae0c52e8970c64/src/app/components/server/post.tsx#L11)
