### ISSUE TITLE
Custom 404 page

### ISSUE THREAD

**Issue by Emmanuel-Develops** [bitcoinsearch/tldr#350]
Current Page
<img width="1783" alt="Screenshot 2024-07-09 at 3 03 53 PM" src="https://github.com/bitcoinsearch/tldr/assets/62019510/3f81e885-1daa-42b8-a95a-aa264e7fd7bc">

Solution:
- No theme for TLDR at the moment, consider having a light theme error page (matching the header in the image above)

Reference -> Bitcoin search Error page
<img width="748" alt="Screenshot 2024-07-09 at 3 16 05 PM" src="https://github.com/bitcoinsearch/tldr/assets/62019510/80459a15-4f73-40d0-b5ca-0f207a7bf338">

**Comment by IgboPharaoh** [comment]
Thank you for bringing this issue to our attention, I'll attend to this issue provide feedback here.

**Comment by IgboPharaoh** [comment]
#361  attends to this issue

**Comment by kouloumos** [comment]
Closed by https://github.com/bitcoinsearch/tldr/pull/361

@IgboPharaoh using the keywords [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) closes the issue automatically when the PR is merged.
