### ISSUE TITLE
inconsistency of text display of combined summaries

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/tldr#40]
This is the combined summary of for the hot topics:

<img width="903" alt="Screenshot 2023-10-13 at 12 51 31 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/fb07b33d-79b6-4125-820e-29baaf7dd74e">

and this is in the all activity:

<img width="890" alt="Screenshot 2023-10-13 at 12 51 40 PM" src="https://github.com/bitcoinsearch/tldr/assets/755825/188e41e8-33eb-4621-a42a-937230f76236">

I'd prefer the top layout for the all activity feed which includes the original author and the other involved in the thread, but at the least we should have the same author (the bottom one show the _latest_ author I believe).

**Comment by IgboPharaoh** [comment]
#41

**Comment by adamjonas** [comment]
I'd prefer the top layout for the all activity feed which includes the original author and the other involved in the thread, but at the least we should have the same author (the bottom one show the latest author I believe).

#41 fixed the author. Would still prefer the active discussions style text display but removing the bug label.

**Comment by IgboPharaoh** [comment]
#42
