### ISSUE TITLE
add rss feed

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/tldr#45]
should be done on the client

**Comment by Emmanuel-Develops** [comment]
@adamjonas could you please add more details on this?

**Comment by adamjonas** [comment]
All summaries. I'm not seeing how we can do daily updates right now.

**Comment by Emmanuel-Develops** [comment]
> All summaries. I'm not seeing how we can do daily updates right now.

We already have a [daily cron job](https://github.com/bitcoinsearch/tldr/blob/main/.github/workflows/update-submodule.yml#L10C14-L10C14) that updates submodules which has the latest `homepage.json` which contains the `header_summary`, `active_posts` and `recent_posts`. 

I'm thinking putting all the summaries in a single rss.xml might have a performance bottleneck for rss readers

**Comment by adamjonas** [comment]
All recent posts for a given month?

**Comment by Emmanuel-Develops** [comment]
I think its daily, let me confirm from urvish.

But its not really an issue as we can add a new object to the `homepage.json` file, or better still I can do all that on the api route so it just return the xml

I think the question is do we do all summaries or monthly summaries?

**Comment by adamjonas** [comment]
Probably monthly. All summaries is likely too much, right?

**Comment by Emmanuel-Develops** [comment]
> Probably monthly. All summaries is likely too much, right?

yes, that's what I think. We can increment the scope gradually and see how it performs

Let me get started on that

**Comment by adamjonas** [comment]
closed via #92
