### ISSUE TITLE
Email digest

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/tldr#48]
Subscribe to a daily or weekly email digest

(This is probably a backend job)

**Comment by nully0x** [comment]
@adamjonas would you prefer we use a third-party service or build from scratch an email service?

**Comment by Extheoisah** [comment]
We should probably use an external service to automate this. Writing it ourselves might not be as robust and efficient as using a dedicated service. We probably won't exhaust a free trial mail count.

**Comment by adamjonas** [comment]
3rd party. We don't need to reinvent the wheel. @nourou4them want to take a shot at setting this up?

**Comment by adamjonas** [comment]
Let's start with a weekly newsletter. 

My guess is that involves a new backend action that aggregates posts from the previous week. It points to the ongoing active discussions but emphasizes summarizes of the new replies and separately summarizes the new threads that have started that week.

**Comment by nourou4them** [comment]
I am taking a look at it @adamjonas

**Comment by Extheoisah** [comment]
In my opinion, I don't think this requires a dedicated backend. We can write a cron job in the nextjs app server and automate the process (with github actions perhaps)

**Comment by nourou4them** [comment]
Yes it will require a certain level of automation in order to retrieve summaries and post to include in the newsletter.
For the subscriptions and the distribution, we may use a 3rd party solution.

**Comment by adamjonas** [comment]
Didn't mean to imply adding a backend. I just meant a new json file generated from a new GH action.

**Comment by nourou4them** [comment]
Here is a first version of the template.
https://us21.campaign-archive.com/?u=adc2c3c2db915408c1fa43a3a&id=9929b64c5b

**Comment by nourou4them** [comment]
All the necessary infrastructure to ship a weekly newsletter is in place.
Waiting for #79 to be done in order to retrieve emails and start sending campaigns.

**Comment by adamjonas** [comment]
In this case, the backend is the mailing list summaries repo where the json will be stored.

**Comment by nourou4them** [comment]
Yes, pretty much.
The json file is the source of the content, then there is a medium level of automation that is done above it.
