### ISSUE TITLE
Today in Bitcoin/LN history

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/tldr#49]
Randomly look back X years, summarize and surface a combined summary discussion with 5+ replies.

**Comment by adamjonas** [comment]
this is a backend search added to the homepage.

**Comment by adamjonas** [comment]
@aassoiants this is two features for me. One is a page of famous posts and the other a randomly surfaced post.

@urvishp80 can you take a shot at adding the latter to the homepage json?

We will need to do some digging to pull together the collection for the former.

**Comment by Extheoisah** [comment]
How do you think we should place this in the UI? As a widget? as a closable floating dialog that is expanded to see more?

**Comment by aassoiants** [comment]
In terms of famous posts, i like [gooGofZ](https://github.com/gooGofZ)'s [Android app](https://github.com/gooGofZ/BitcoinTimechainWidgets/tree/main). 

It's a widget that pulls different famous posts. Unsure which database they get them from tho. But maybe we can pull from it if it's open source?

**Comment by aassoiants** [comment]
Fun example of a famous post/ big historic landmark [here](https://twitter.com/ck_snarks/status/1729500416621109389)

This isn't for pulling past quotes from TLDR archives

**Comment by adamjonas** [comment]
To start, I'd like to add this between active posts and all activity. It's just two posts and so it shouldn't take up too much room.
