### ISSUE TITLE
Add some modification to the daily summary paragraph

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/tldr#53]
The daily summary paragraph need some updates in order to upgrade its clarity:

- The text size is way too big compared to other texts on the website.
- The used font is not coherent with the other fonts on the website.
- The text is packed into one paragraph. It would be good to separate it into multiple paragraphs.

**Comment by adamjonas** [comment]
@urvishp80 can we look at modifying the prompt to make it multi paragraph please?

**Comment by adamjonas** [comment]
There are new lines in the [summary](https://github.com/bitcoinsearch/mailing-list-summaries/commit/779229e2dd23b0dd8aa593f9e26665861c569826). We need to render it.
