### ISSUE TITLE
Add a description for the website

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/tldr#54]
Add a description for the website for more clarity for users.
It can be located between the "TLDR" and "Your daily summary" titles. 

You can put the same description that is on this repo readme: "presents summaries of the [bitcoin-dev](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/) and [lightning-dev](https://lists.linuxfoundation.org/pipermail/lightning-dev/) mailing lists. We intend to add other sources like StackExchange in the future."

![Screenshot from 2023-11-01 14-51-18](https://github.com/bitcoinsearch/tldr/assets/43266768/a04091b0-36f5-420e-af04-3aab7818576d)

**Comment by adamjonas** [comment]
I don't think the second sentence is a useful addition for a site description

**Comment by nourou4them** [comment]
> I don't think the second sentence is a useful addition for a site description

Yes you are right.

**Comment by Extheoisah** [comment]
Where do you imagine this would live in the UI?
