### ISSUE TITLE
Modify the "Search" box behavior

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/tldr#56]
Context: Currently, when we click in the "Search" box, it opens pop up where the search is done, with some filters.

Idea: Allow the searching directly in the "Search" box and add the filters (the ones displayed in the pop up) in it.

![Screenshot from 2023-11-01 15-12-23](https://github.com/bitcoinsearch/tldr/assets/43266768/22e629e9-e30d-417a-b9da-7011c3a8f099)

**Comment by adamjonas** [comment]
Can you provide a clearer visual of what you mean in such a confined space?

**Comment by nourou4them** [comment]
I think there is no need to have a pop up.
Mostly an adaption of the "Search" box size to show these filters, only once we click on it.

![image](https://github.com/bitcoinsearch/tldr/assets/43266768/8d7dbde6-84be-4e33-9d07-47af660c94c4)

**Comment by adamjonas** [comment]
@Extheoisah any input here?

**Comment by Extheoisah** [comment]
@nourou4them while that might be good UX for search, I don't think there will be a good UX and real estate for showing the result of the search query. or do you have a suggestion on how that will be rendered in the UI given we don't show the pop-up?

**Comment by nourou4them** [comment]
Thank you @Extheoisah.
I was thinking about something like this, which is the continuity of the search box.
What do you think?

![image](https://github.com/bitcoinsearch/tldr/assets/43266768/16759fb2-40b7-43d2-aa97-34e0502278ac)

**Comment by Extheoisah** [comment]
This makes sense. We can do this, just need to switch the position.

**Comment by adamjonas** [comment]
Ref #90
