### ISSUE TITLE
Add some separator between sections

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/tldr#57]
Context: When visiting the website, we can see a lot information and an uninformed user could miss some discussions on the way due to the fact that there are not clearly separated, even if they are well organised.

Idea: Add separators between discussions or add a shadow under each section (or each 2 sections).

![Screenshot from 2023-11-01 15-22-40](https://github.com/bitcoinsearch/tldr/assets/43266768/b15e1af7-d1ac-4f1b-9413-d2fb3ad3e945)

**Comment by nourou4them** [comment]
Exemple of separators:
![Screenshot from 2023-11-01 16-24-12](https://github.com/bitcoinsearch/tldr/assets/43266768/1c30e211-9ecf-4cc9-951a-435f065c58df)

**Comment by maheshchandra10** [comment]
Since you haven't mentioned how much gap you need between the separators, I have added it from my side which seemed best to me in the linked PR. Let me know if you want to increase or decrease the gap otherwise.

**Comment by nourou4them** [comment]
I think the gap is perfect.
It would be cool if the separators are more visible, with a dark grey or black.

**Comment by adamjonas** [comment]
I'm happy with a more subtle one to start if that's ok @nourou4them
