### ISSUE TITLE
Add information about how datas are used

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/tldr#58]
Context: Visitors have no information on which of their data are collected on for which purpose.

Idea: Add a banner or a dedicated page in which the following information will appear:

- Which data are collected?
- For what purpose(s)?
- How many time will the data be kept?
- How to access them?

**Comment by adamjonas** [comment]
I think this can be closed. The data we track is transparently found on the umami link in the footer.

**Comment by nourou4them** [comment]
It would be something like this, found in the savingsatoshi doc page:
![Screenshot from 2023-11-02 00-59-48](https://github.com/bitcoinsearch/tldr/assets/43266768/ddda7fc1-a88f-4b68-af84-9787563c2750)

**Comment by nourou4them** [comment]
Linked to #59

**Comment by Extheoisah** [comment]
IMO, I don't think we need this. We don't save or track any private data and the umami dashboard is available publicly for users.

**Comment by nourou4them** [comment]
In fact, the ip address for example, among the other collected data, is considered a private data in the EU (RGPD rule).
Some other bitcoin dev community projects have added this mention in their website, which is coherent.
You can see the example I added in #59 , in the About page.

**Comment by adamjonas** [comment]
We don't collect or save IPs. We save regions only. We can add a line about us not storing IPs but largely I agree with Theo.

**Comment by nourou4them** [comment]
Is the region a data derived from the ip adress?
Also, what about the browser, the OS and the device?
Combined with the region, all these information could be considered personal data.

But, let me know if I should update the Privacy part of the about page.

**Comment by Extheoisah** [comment]
Since we're adding a documentation page (https://github.com/bitcoinsearch/tldr/issues/59), we could just put this info there if we want to.

**Comment by nourou4them** [comment]
It was already added there.
Waiting for a final validation from @adamjonas .

**Comment by adamjonas** [comment]
We don't store the IP. How it is derived is based on umami but we don't have any PII in our possession. We can add what we store to the about page but IP addresses are not being collected.

**Comment by nourou4them** [comment]
Ok. Then the Privacy part of the documentation page have already enough information.
The overall page can be validated as it is.
