### ISSUE TITLE
add menu to navigate to all activity, hot discussions and other future sections (e.g. irc/spec meeting summaries and this day in bitcoin history)

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/tldr#64]

**Comment by Extheoisah** [comment]
Similar to this?
![image](https://github.com/bitcoinsearch/tldr/assets/60826700/43700a3e-3a37-4e53-b00b-6e5925984ed3)

**Comment by adamjonas** [comment]
Needs design feedback. Skip for now.

**Comment by adamjonas** [comment]
For mobile, fold search input down to just the magnifying glass.

Hamburger for both desktop and mobile (🍔 4 all!).

Menu items should be:

- Active Discussions
- Today in Bitcoin/LN History
- All Activity
- Newsletter
- RSS feed

**Comment by aassoiants** [comment]
Mentioning https://github.com/bitcoinsearch/tldr/issues/49 so that we don't forget to add once ready
