### ISSUE TITLE
Replace Sender and Receiver by their names in summaries

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/tldr#77]
Context: Sometimes, the sender and the receiver(s) of an email are identified by these titles in summaries, instead of their names.

Solution: Identify senders and receivers by their full names.

![image](https://github.com/bitcoinsearch/tldr/assets/43266768/bc43501b-387f-438e-b90a-f19eb68bf71a)

**Comment by Extheoisah** [comment]
This is a task for @urvishp80 I guess. What I'm not sure of is if he'll have to regenerate the summaries again to effect this change.

**Comment by adamjonas** [comment]
Not possible without mapping all emails to names. Closing.
