### ISSUE TITLE
Sometimes, only 2 participants are mentioned in a summary

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/tldr#78]
Context: Sometimes, only 2 participants are mentioned in a summary

Solution: To group all participants or to mention them all.

![image](https://github.com/bitcoinsearch/tldr/assets/43266768/cc7a961b-75ac-4aeb-aa4f-2216b7f3a0da)

**Comment by Extheoisah** [comment]
This is beyond the scope of the frontend. This issue should be moved to the [mailing-list-summaries backend](https://github.com/bitcoinsearch/mailing-list-summaries/issues)
