### ISSUE TITLE
Search author input box cutoff (mobile)

### ISSUE THREAD

**Issue by adamjonas** [bitcoinsearch/tldr#90]
![image](https://github.com/bitcoinsearch/tldr/assets/755825/33c0f3c7-e0be-4b4e-870d-ce2c1fbe9f6b)

**Comment by Extheoisah** [comment]
How can I recreate this issue? i don't see the issue on mobile

**Comment by Extheoisah** [comment]
I was able to recreate the issue on safari. fixed here -> #91
