### ISSUE TITLE
The search box shouldn't move when querying it

### ISSUE THREAD

**Issue by nourou4them** [bitcoinsearch/tldr#94]
Context: There is this weird behavior where, when scrolling and suddenly wanting to do a search, clicking on the search button will take you to the top of the homepage.

Could the user do a search without being taken back to the top of the page?

[tldr_search.webm](https://github.com/bitcoinsearch/tldr/assets/43266768/e6c16556-c9ee-4960-bb1a-2d107fc63f52)

**Comment by adamjonas** [comment]
This video doesn't load for me

**Comment by nourou4them** [comment]
Which browser are you using?
It works on Brave and Mozilla, with and without logging into my github account.

**Comment by IgboPharaoh** [comment]
#118 attends to this issue
